spring:
  freemarker:
    cache: false
    charset: UTF-8
    suffix: .html
    enabled: true
    content-type: text/html
    template-loader-path: classpath:/templates/

#  thymeleaf:
#    prefix: classpath:/templates/
#  mvc:
#    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall?ullNamePatternMatchesAll=true&amp;serverTimezone=GMT%2b8?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  application:
    name: shopping
server:
  port: 8763
feign:
  hystrix:
    enabled: true




